### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by cepxeo** [plackyhacker/SysCalls#1]
Hi, was trying this, but getting an error upon execution:

SharpCall.exe
[+] Base Address of ntdll is 0x774E0000
[+] Target PID is 408
[+] Syscall NtOpenProcess on 408

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at System.Runtime.InteropServices.Marshal.CopyToManaged(IntPtr source, Object destination, Int32 startIndex, Int32 length)
at System.Runtime.InteropServices.Marshal.Copy(IntPtr source, Byte[] destination, Int32 startIndex, Int32 length)
at SysCall.Syscalls.GetSysCallId(String FunctionName)
at SysCall.Syscalls.NtOpenProcess(IntPtr& ProcessHandle, UInt32 AccessMask, OBJECT_ATTRIBUTES& ObjectAttributes, CLIENT_ID& ClientId)
at SysCall.Program.Main(String[] args)

**Comment by plackyhacker** [comment]
Hi, what is the target process? Does it exist? Do you have privs to open it?

**Comment by cepxeo** [comment]
Only changed the payload, process is notepad. It exists, tried from both user and admin contexts. Windows versions tested 1809 and 21H1.

When the notepad is not open, error is different:

SharpCall.exe
[+] Base Address of ntdll is 0x774E0000

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SysCall.Program.Main(String[] args)

**Comment by cepxeo** [comment]
Ok, got my problem. Was building for Any CPU in VS which seems to not be a good option. x64 made it work. Many thanks for your reply.

**Comment by plackyhacker** [comment]
Yeah, I've had that issue before too. 👍
